version: "3.9"
services:
    web:
        container_name: web
        build: nginx
        ports:
          - 80:80
        depends_on:
          - api
        networks:
          - local-net
    api:
        container_name: api
        build: .
        ports:
          - 8000:8000
        networks:
          - local-net
        expose:
          - 8000
networks:
  local-net:
    driver: bridge